### ISSUE TITLE
Figure out better separation for coinbin dependencies

### ISSUE THREAD

**Issue by kimdhamilton** [WebOfTrustInfo/btcr-tx-playground.github.io#30]
This codebase is now based on coinb.in, and many of the js files are directly copied from its repo [https://github.com/OutCast3k/coinbin](https://github.com/OutCast3k/coinbin).

To make it easier to keep our codebase up to date with coinb.in, it would be nice to copy in dependencies as a build step. The problem is that the coinb.in codebase isn't configurable for the things we need to customize.

We need to change the following files, as shown in the diff image. (Note that btcrDidUtils.js is only needed by the BTCR wallet)

- coin.js
- coinbin.js

![coinbin_diff](https://user-images.githubusercontent.com/3945683/63285238-2a174200-c26a-11e9-905b-ea2c0cda5e8d.png)

Look into ways to keep these codebases synchronized for the future. Would it be possible to submit a PR to coinb.in, to make it easier to configure these items?

**Comment by hawkmauk** [comment]
Update: I've done some more testing on the changes that I've made and it appears to have only gone someway to separating the two as there are changes to index.html that need to be accounted for due to the change to the bitcoin testnet provider.
I'm looking at this now and am wondering if it would be best to use xslt to build the btcr version of index.html directly from the coinbin repo and injecting the btcr changes.

**Comment by hawkmauk** [comment]
I've followed up on my previous comment and completed separation from the coinbin dependencies by creating `index.xsl` to build the btcr playground.
A testnet endpoint still needs to be provided but this should be added upstream in the coinb.in repo.  We can then modify `index.xsl` to change the default settings.
I've created pull request #32 to merge the changes into this repo

**Comment by hawkmauk** [comment]
Fixed by #32
